# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# # Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# # See: https://circleci.com/docs/2.0/orb-intro/
# orbs:
#   node: circleci/node@4.7

jobs:
  build:
      docker: # executor type
        - image: circleci/node:13.8.0 # primary container will run the latest, production-ready base image
      steps:
        - checkout
        - run: npm i
        - save_cache:
            key: "npm-packages"
            paths:
              - /src/node_modules
        - run: npm run list

  test:
      docker: # executor type
        - image: circleci/node:13.8.0 # primary container will run the latest, production-ready base image
      steps:
        - checkout
        - run: npm i
        - restore_cache:
            key: "npm-packages"
        - run: npm i
        - run: npm run test

  analyse:
      docker: # executor type
        - image: circleci/node:13.8.0 # primary container will run the latest, production-ready base image
      steps:
        - checkout
        - restore_cache:
            key: "npm-packages"
        - run: npm audit

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test:
          requires:
            - build
      - analyse:
          requires:
            - test
