# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
# commands:
#   print_pipeline_id:
#     description: "A very simple command for demonstration purposes"
#     steps:
#       - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  build:
      docker: # executor type
        - image: circleci/node:13.8.0 # primary container will run the latest, production-ready base image
      steps:
        - checkout
        - run: npm i
        - save_cache:
            key: "npm-packages"
            paths:
              - /src/node_modules
        - run: npm run lint

  test:
      docker: # executor type
        - image: circleci/node:13.8.0 # primary container will run the latest, production-ready base image
      steps:
        - checkout
        - run: npm i
        - restore_cache:
            key: "npm-packages"
        - run: npm i
        - run: npm run test

  analyse:
      docker: # executor type
        - image: circleci/node:13.8.0 # primary container will run the latest, production-ready base image
      steps:
        - checkout
        - restore_cache:
            key: "npm-packages"
        - run: npm audit

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test:
          requires:
            - build
      - analyse:
          requires:
            - test
